AWSTemplateFormatVersion: '2010-09-09'
cddf
Description: Multi-Region EC2 Migration using AWS Application Migration Service

Parameters:
  SourceRegion:
    Type: String
    Description: The AWS region of the source EC2 instance
  TargetRegion:
    Type: String
    Description: The AWS region where the EC2 instance will be migrated
  SourceServerId:
    Type: String
    Description: The ID of the source EC2 instance in the source region
  TargetServerName:
    Type: String
    Description: The name of the migrated EC2 instance in the target region
  ReplicationJobName:
    Type: String
    Description: The name of the replication job for the migration
  ReplicationSubnetId:
    Type: String
    Description: The ID of the subnet for replication in the target region
  ReplicationSecurityGroupId:
    Type: String
    Description: The ID of the security group for replication in the target region

Resources:
  MigrationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-MigrationServiceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sms.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SMSRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
                  - s3:CreateBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:GetBucketTagging
                  - s3:PutBucketTagging
                  - s3:DeleteBucketTagging
                  - ec2:Describe*
                  - ec2:Get*
                  - ec2:List*
                  - ec2:Attach*
                  - ec2:Detach*
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:RunInstances
                  - ec2:TerminateInstances
                Resource: '*'

  SMSReplicationJob:
    Type: AWS::SMS::ReplicationJob
    Properties:
      ReplicationJobId: !Sub ${AWS::StackName}-ReplicationJob
      ServerId: !Ref SourceServerId
      SeedReplicationTime: '1970-01-01T00:00:00Z'
      Frequency: 30
      LicenseType: AWS
      RoleName: !GetAtt MigrationServiceRole.Arn
      Description: Replication job for EC2 instance migration
      NumberOfRecentAmisToKeep: 2
      Encrypted: false
      KmsKeyId: ''
      RunOnce: true
      NextReplicationRunStartTime: '1970-01-01T00:00:00Z'
      Tags:
        - Key: Name
          Value: EC2Migration
        - Key: MigrationType
          Value: AWS SMS

  TargetEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref my-key-pair
      SubnetId: !Ref ReplicationSubnetId
      SecurityGroupIds:
        - !Ref ReplicationSecurityGroupId
      Tags:
        - Key: Name
          Value: !Ref TargetServerName
  
